### ISSUE TITLE
确定增加了异步消息？

### ISSUE THREAD

**Issue by hejun311** [ArcherGu/QTWebChat_JS#39]
export function sendMsg(msg) {
    return apiClient.send({
        action: 'send-msg',
        data: msg
    });
}

export function sendSyncMsg(msg) {
    return apiClient.send({
        action: 'send-msg-sync',
        data: msg
    });
}

**Comment by ArcherGu** [comment]
不好意思，这个项目是很久以前的，异步消息应该是增加了，但是我无法确定。而且现在也没有维护这个项目了。
